### ISSUE TITLE
Installing go4 error

### ISSUE THREAD

**Issue by melardev** [go4org/go4#52]
Hi, I tried to add the module in my project but I get this error:

```
go: finding github.com/go4org/go4 latest
go get: github.com/go4org/go4@v0.0.0-20200411211856-f5505b9728dd: parsing go.mod:
	module declares its path as: go4.org
	        but was required as: github.com/go4org/go4
```

What is the fix? I am not able to find any installation instructions.

**Comment by dmitshur** [comment]
The fix is to use a matching module path, which is `go4.org`. You can see it declared at the top of the [`go.mod` file](https://github.com/go4org/go4/blob/f5505b9728ddf920bb673137648788c5ac99de1b/go.mod#L1).

If you visit the documentation for one of the packages in this module, for example, [`go4.org/osutil`](https://pkg.go.dev/go4.org/osutil), you can see the import path at the top, with a button to copy it to clipboard:

![image](https://user-images.githubusercontent.com/1924134/88294610-78c72a80-ccca-11ea-94cc-23d146454c34.png)

**Comment by melardev** [comment]
@dmitshur You are right, `import "go4.org/strutil"` fixed my issue, thanks!

**Comment by dmitshur** [comment]
No problem.

@melardev Out of curiosity, did you find the previous invalid "github.com/go4org/go4/strutil" import path written down or suggested somewhere? I'm asking because if there was some resource that made you think that's what you should write, we should try to fix or update it, so that other people don't get misled in the same way.

**Comment by melardev** [comment]
@dmitshur No, It was just trying to guess it.
I wanted to test the ContainsFold from this [link](https://gowalker.org/go4.org/strutil) function from strutil, all I knew is it belongs to go4org, I went to this Repo but there were no instructions on install, so I decided to "guess" the import path, that should be "github.com/go4org/go4/strutil", but it failed, this is why I opened this issue.
